SELECT 'PTT.BK' AS ticker, 'PTT' AS company_name, 'Energy' AS sector, 'LARGE' AS market_cap_tier
UNION ALL SELECT 'KBANK.BK', 'Kasikornbank', 'Banking', 'LARGE'
UNION ALL SELECT 'SCB.BK', 'SCB X', 'Banking', 'LARGE'
UNION ALL SELECT 'ADVANC.BK', 'Advanced Info Service', 'ICT', 'LARGE'
UNION ALL SELECT 'AOT.BK', 'Airports of Thailand', 'Transport', 'LARGE'
UNION ALL SELECT 'CPALL.BK', 'CP ALL', 'Commerce', 'LARGE'
UNION ALL SELECT 'SCC.BK', 'Siam Cement', 'Construction', 'LARGE'
UNION ALL SELECT 'GULF.BK', 'Gulf Energy', 'Energy', 'LARGE'
UNION ALL SELECT 'BDMS.BK', 'Bangkok Dusit Medical', 'Health', 'LARGE'
UNION ALL SELECT 'TRUE.BK', 'True Corporation', 'ICT', 'LARGE'
UNION ALL SELECT 'DTAC.BK', 'Total Access (Merged)', 'ICT', 'LARGE'
UNION ALL SELECT 'MINT.BK', 'Minor International', 'Food & Hotel', 'LARGE'
UNION ALL SELECT 'TOP.BK', 'Thai Oil', 'Energy', 'LARGE'
UNION ALL SELECT 'BH.BK', 'Bumrungrad Hospital', 'Health', 'LARGE'
UNION ALL SELECT 'CPN.BK', 'Central Pattana', 'Property', 'LARGE'
UNION ALL SELECT 'HMPRO.BK', 'Home Product Center', 'Commerce', 'LARGE'
UNION ALL SELECT 'IVL.BK', 'Indorama Ventures', 'Petrochem', 'LARGE'
UNION ALL SELECT 'KTB.BK', 'Krung Thai Bank', 'Banking', 'LARGE'
UNION ALL SELECT 'BBL.BK', 'Bangkok Bank', 'Banking', 'LARGE'
UNION ALL SELECT 'PTTEP.BK', 'PTT Exploration', 'Energy', 'LARGE'